import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';


//(1) add 3 words to each card
//(2) the user needs to figure out the single word that is formed when the 3 words are combined phonetically and guess which object is the answer to the riddle
//(3) one card contains 4 objects, or words in this case, and the user needs to guess which one of the 4 objects is the answer to the riddle.
//    the 3 other objects are combined to form a word phonetically
//(4) Then, after the user answers correctly, there will be 2 words leftover for each card (2*4 = 8 words in total)
//(5) The 8 words can form a few sentences which is part of a story (like Mad Libs)


const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const METADATA_DIR = path.join(__dirname, 'generated_metadata');

const genAI = new GoogleGenerativeAI('AIzaSyBYMgBPE9yzVZeYsT6np_K6Y-pOHiiOvsc');
async function generateWords() {
    const prompt = `Generate exactly 3 words that sound like a single real word when combined phonetically, followed by that combined word. Output ONLY the 4 words separated by commas on a single line. No explanations, no numbering, no extra text. Example format: Sea, Weed, Shell, Seashell`;
    

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
      const response = await model.generateContent(prompt);
      const word = response.response.text().trim();

      return word;

 
    } catch (error) {
      console.error(error);
    }
}

//3 words which form a single word when combined phonetically

const word = '';
const card1 = [], card2 = [], card3 = [], card4 = [];
//story deck: each contains 2 words and used for the Mad Libs style story at the end
const sen1 = [], sen2 = [], sen3 = [], sen4 = [];

//MAKE SURE IT IS ALL SFW.
//(1) get 4 riddles and answers from API League
//(2) add the answer to the riddle to one of the 4 cards


const riddles = [];
const url = 'https://riddles-api.vercel.app/random';

(async () => {
    try {
        // Generate words for each card first
        const wordResults = await Promise.all([generateWords(), generateWords(), generateWords(), generateWords()]);
        const cards = [card1, card2, card3, card4];
        const sens = [sen1, sen2, sen3, sen4];
        for (let i = 0; i < wordResults.length; i++) {
            const words = wordResults[i].split(',').map(w => w.trim()).filter(w => w.length > 0);
            const combinedWord = words.pop(); // last word is the phonetic answer
            sens[i].push(combinedWord);
            for (const word of words) {
                cards[i].push(word);
            }
        }

        // Fetch 4 riddles with single-word answers sequentially
        while (riddles.length < 4) {
            const response = await fetch(url);
            if (!response.ok) {
                throw new Error(`HTTP error! Status: ${response.status}`);
            }
            const data = await response.json();
            if (data.answer.trim().split(/\s+/).length === 1) {
                riddles.push({ question: data.riddle, answer: data.answer.trim() });
            }
            await new Promise(resolve => setTimeout(resolve, 300));
        }

        // Push riddle answers into each card and sen
        card1.push(riddles[0].answer);
        card2.push(riddles[1].answer);
        card3.push(riddles[2].answer);
        card4.push(riddles[3].answer);
        sen1.push(riddles[0].answer);
        sen2.push(riddles[1].answer);
        sen3.push(riddles[2].answer);
        sen4.push(riddles[3].answer);

        console.log('card1:', card1, 'sen1:', sen1);
        console.log('card2:', card2, 'sen2:', sen2);
        console.log('card3:', card3, 'sen3:', sen3);
        console.log('card4:', card4, 'sen4:', sen4);

        const story = await generateStory(sen1, sen2, sen3, sen4);
        console.log('\nStory:\n', story);

    } catch (error) {
        console.error('There was a problem with the fetch operation:', error);
    }
})();
//Gemini creates a story using the 8 words leftover after the user answers the riddles correctly. The story should be fun and engaging, and the 8 words should be used in a creative way to form a cohesive narrative. The story can be in any genre, such as adventure, mystery, comedy, etc., and should be suitable for all ages. 
//It will be like Mad Libs, where the user uses the words from sen1, sen2, sen3, and sen4 to fill in the blanks of a story template. The story will be generated by Gemini based on the words provided by the user. The story should be entertaining and make use of the words in a way that is both creative and coherent.

//CODE HERE

async function generateStory(sen1, sen2, sen3, sen4) {
    const words = [...sen1, ...sen2, ...sen3, ...sen4];
    const prompt = `You are writing a fun, short Mad Libs-style story suitable for all ages. You must use ALL of the following 8 words exactly as given, in any order, within the story: ${words.join(', ')}. Write a single cohesive narrative of 4-6 sentences. Any genre is fine (adventure, comedy, mystery, etc.). Output only the story text, nothing else.`;

    try {
        const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
        const response = await model.generateContent(prompt);
        return response.response.text().trim();
    } catch (error) {
        console.error(error);
    }
}












