services:
  - type: web
    name: gist
    runtime: node
    rootDir: myapp
    buildCommand: npm install && npm run build
    startCommand: node build
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 20
